#!/bin/sh
# Script to generate standard html tags and ready a file to write PHP in

# I Want to generate basic html

make_html()
{
echo "<!DOCTYPE html>\n\
<!-- html file for ${PHP_OUTPUT}\n\
<html>\n\t\
<head>\n\t\t\
<title>\n\t\t\
</title>\n\t\
<body>\n\n\t\
</body>\n\
</html>" >> ${PHP_OUTPUT}.html;
}

make_css() {
	echo "/* CSS for ${PHP_OUTPUT}.css */"\
	>> ${PHP_OUTPUT}.css
}

if [ $# = 0 ]; 
then
	echo "Error, exiting";
	echo "Usage $0 {FILENAME.php}";
	exit 1;
elif [ $# = 1 ];
then
	PHP_OUTPUT=$1;	# We hook the variable number 1 to PHP_OUTPUT.
	make_html;
	make_css;
	echo "File $PHP_OUTPUT ready for editing -\
		- if you want vim to snap\
		 in, use\n .$0 {filename.php} vim";
	exit 0;
elif [ $# = 2 ];
then
	PHP_OUTPUT=$1;	# We hook the variable number 1 to PHP_OUTPUT.
	make_html;
	make_css;
	echo "Snapping to vim";
	vim -O $(pwd)/${PHP_OUTPUT}.html $(pwd)/${PHP_OUTPUT}.css
	exit 0; 
fi	
