#!/bin/bash
# script to make sure external drives are mounted

# whattodo command  /dev/disk CryptContainerVolumeGroup
cryptsetup luksOpen /dev/sda5 TestVG

# Generic Hard disk variables
block1=/dev/sdc1
block2=/dev/sdd1
block3=/dev/mapper/testvg-1TB

# Generic mount points in /mnt
ext1=/mnt/ext1
ext2=/mnt/ext2
ext3=/mnt/ext3

# First check if sd{c,d,e}1 is available for mount, then mount it
[ -b ${block1} ] && [ -d ${ext1} ] && mount ${block1} ${ext1}
[ -b ${block2} ] && [ -d ${ext2} ] && mount ${block2} ${ext2}
[ -b ${block3} ] && [ -d ${ext3} ] && mount ${block3} ${ext3}

# another round of tests, this time recursively mod owner's group  
# will only chgrp if two previous tests return without fail
#[ -b ${block1} ] && [ -d ${ext1} ] && chgrp -R storage ${ext1}
#[ -b ${block2} ] && [ -d ${ext2} ] && chgrp -R storage ${ext2}
#[ -b ${block3} ] && [ -d ${ext3} ] && chgrp -R storage ${ext3}

# Check if lynzh is in group 'storage', else add him to that group
CHECK_STORAGE() { groups lynzh 2>&1 | grep -o storage }
[ -n CHECK_STORAGE ] && exit 0 || [ -z CHECK_STORAGE ] && gpasswd -a lynzh storage;


