#!/bin/bash
# script to make sure external drives are mounted

# Generic Hard disk variables
block1=/dev/sdc1
block2=/dev/sdd1
block3=/dev/sdf1

# Generic mount points in /mnt
ext1=/mnt/ext1
ext2=/mnt/ext2
ext3=/mnt/ext3

# First check if sd{c,d,e}1 is available for mount, then mount it
[ -b ${block1} ] && [ -d ${ext1} ] && mount ${block1} ${ext1}
[ -b ${block2} ] && [ -d ${ext2} ] && mount ${block2} ${ext2}
[ -b ${block3} ] && [ -d ${ext3} ] && mount ${block3} ${ext3}

# another round of tests, this time recursively mod owner's group  
# will only chgrp if two previous tests return without fail
[ -b ${block1} ] && [ -d ${ext1} ] && chgrp -R storage ${ext1}
[ -b ${block2} ] && [ -d ${ext2} ] && chgrp -R storage ${ext2}
[ -b ${block3} ] && [ -d ${ext3} ] && chgrp -R storage ${ext3}


# Let user read from disks, this may fuckup ntfs disks or not
[ -b ${block1} ] && [ -d ${ext1} ] && chmod -R 755 ${ext1}
[ -b ${block2} ] && [ -d ${ext2} ] && chmod -R 755 ${ext2}
[ -b ${block3} ] && [ -d ${ext3} ] && chmod -R 755 ${ext3}

# last, add user to group \storage\
gpasswd -a lynzh storage

# that last step needs a check
