#!/bin/bash
# script to make sure external drives are mounted

# Generic Hard disk variables
disk1=/dev/sdc1
disk2=/dev/sdd1
disk3=/dev/sdf1

# Generic mount points in /mnt
ext1=/mnt/ext1
ext2=/mnt/ext2
ext3=/mnt/ext3


# First check if sd{c,d,e}1 is available for mounting
[ -b ${disk1} ] && [ -d ${ext1} ] && mount ${disk1} ${ext1}
[ -b ${disk2} ] && [ -d ${ext2} ] && mount ${disk2} ${ext2}
[ -b ${disk3} ] && [ -d ${ext3} ] && mount ${disk3} ${ext3}




# Add external disks to group storage, needs check if groups exist
chgroup storage /mnt/ext1;
chgroup storage /mnt/ext2;

# Let users read from external disks
chmod 755 /mnt/ext1; 
chmod 755 /mnt/ext2;

# add user to group \storage\
usermod -G storage lynzh

[ -b /dev/sdc1 ] && [ -d /mnt/ext1 ] && \
ln -s /mnt/ext1 $HOME/ext1;

[ -b /dev/sdd1 ] && [ -d /mnt/ext2 ] && \
ln -s /mnt/ext2 $HOME/ext2;

