#!/bin/sh
#
# Script to test getopts

NAME=''
HOSTPORT=''
TEMP=$(getopts n:T:S:h "$%")

if [ $? != 0 ] ; then echo "Terminator stole this script" >&2 ; exit 1 ; fi

eval set -- "$TEMP"

while true ; do
	case "$1" in
			-n) NAME=$2 ; shift 2;;
			-T) HOSTPORT=$2 ; shift 2;;
			-S)
					if [ -r $2 ]; then
							SECRET="-S $2";
					else
							info "Secret file $2 not readable."
							exit 1;
					fi
					shift 2;;
			-h) echo "Usage .."; exit 0 ;;
			--) shift; break;;
			*) echo "internal error"; exit 1;;
	esac
done
